Auth-Server/auth_server/auth_server/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    
    # User management and main web application
    url(r'^', include('users.urls', namespace='users')),
    url(r'^rest/', include('recordings.urls', namespace='recordings')),
    
    # REST auth system
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
)

Auth-Server/auth_server/users/urls.py
from django.conf.urls import patterns, url, include
from rest_framework.authtoken import views as rest_views
from users import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	
	# Token authentication: token generator
	# Documentation here: http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication
	# You can retrieve a user token making a POST to this REST API
	# with username and password in a JSON.
    # Example of REST queries with curl:
	# curl -X POST http://localhost:8000/rest/token/get/ -H "Content-Type: application/json" -d '{"username":"<username>", "password":"<password>"}'
	# curl -X POST http://localhost:8000/rest/token/renew/ -H "Content-Type: application/json" -H "Authorization: Token abcdefghijklmnopqrstuvwxyz0123456789abcd"
    url(r'^rest/token/get/$', rest_views.obtain_auth_token, name='gettoken'),
    url(r'^rest/token/renew/$', views.tokenRenewREST.as_view(), name='renewtoken'),
    
    
	# Access management
	url(r'^accounts/login/$', views.login, name='login'),
	url(r'^accounts/logout/$', views.logout, name='logout'),
	
	# User management
	url(r'^users/register/$', views.register, name='register'),
	url(r'^users/activation/$', views.activation, name='activation'),
	url(r'^users/reset/$', views.resetPassword, name='resetpassword'),
	url(r'^users/password/$', views.changePassword, name='password'),
	url(r'^users/delete/$', views.delete, name='delete'),
	url(r'^users/update/$', views.update, name='update'),
	url(r'^users/admin/$', views.adminUpdate, name='adminupdate'),
)

Auth-Server/auth_server/users/models.py
from django.db import models
from django.conf import settings

# Required for Token authentication:
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

# Create your models here.
class ActivationLink(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, unique=True)
	link = models.CharField(max_length=50)
	
	def __unicode__(self):  # Python 3: def __str__(self):
		return 'Activation link for ' + str(self.user)

class PasswordResetLink(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, unique=True)
	link = models.CharField(max_length=50)
	
	def __unicode__(self):  # Python 3: def __str__(self):
		return 'Password reset link for ' + str(self.user)



# Token authentication
# After creating a new user call this function that create a new token for him.
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

Auth-Server/auth_server/users/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse

import django.contrib.auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

from rest_framework.authtoken.models import Token
from rest_framework.views import APIView
from rest_framework.renderers import JSONRenderer
from rest_framework import permissions
import json

from django.conf import settings
from django.utils.crypto import get_random_string
from django.core.mail import send_mail

from users.models import ActivationLink, PasswordResetLink



def generateLink():
	chars = 'abcdefghijklmnopqrstuvwxyz0123456789'
	return get_random_string(50, chars)



def sendRegistrationLink(request, user):
	subject = 'Activation link'
	from_email = 'No Reply <' + settings.EMAIL_HOST_USER + '>'
	
	link = generateLink()
	while ActivationLink.objects.filter(link=link).exists():
		link = generateLink()
	linkobj, created = ActivationLink.objects.get_or_create(user=user)
	linkobj.link = link
	linkobj.save()
	
	url = request.build_absolute_uri(reverse('users:activation'))
	url += '?key=' + link
	
	message = 'Dear ' + user.username + ',\n'
	message += 'thanks for your registration.\n'
	message += 'Please use next link in order to activate your account.\n'
	message += url + '\n'
	message += 'If you can\'t follow the link, just copy the url and paste it in the browser.\n\n'
	message += 'If you didn\'t requested a new account just ignore this email.'
	
	html_message = '<p>Dear ' + user.username + ',<br />'
	html_message += 'thanks for your registration.<br />'
	html_message += 'Please use next link in order to activate your account.<br />'
	html_message += '<a href="' + url + '">' + url + '</a><br />'
	html_message += 'If you can\'t follow the link, just copy the url and paste it in the browser.</p>'
	html_message += '<p>If you didn\'t requested a new account just ignore this email.</p>'
	
	mail = send_mail(subject, message, from_email, [user.email], fail_silently=settings.DEBUG, html_message=html_message)



def sendPasswordResetLink(request, user):
	subject = 'Password reset link'
	from_email = 'No Reply <' + settings.EMAIL_HOST_USER + '>'
	
	link = generateLink()
	while PasswordResetLink.objects.filter(link=link).exists():
		link = generateLink()
	linkobj, created = PasswordResetLink.objects.get_or_create(user=user)
	linkobj.link = link
	linkobj.save()
	
	url = request.build_absolute_uri(reverse('users:password'))
	url += '?key=' + link
	
	message = 'Dear ' + user.username + ',\n'
	message += 'you requested a password reset.\n'
	message += 'Please use next link in order to reactivate your account.\n'
	message += url + '\n'
	message += 'If you can\'t follow the link, just copy the url and paste it in the browser.'
	
	html_message = '<p>Dear ' + user.username + ',<br />'
	html_message += 'you requested a password reset.<br />'
	html_message += 'Please use next link in order to reactivate your account.<br />'
	html_message += '<a href="' + url + '">' + url + '</a><br />'
	html_message += 'If you can\'t follow the link, just copy the url and paste it in the browser.</p>'
	
	mail = send_mail(subject, message, from_email, [user.email], fail_silently=settings.DEBUG, html_message=html_message)



# Access control views

@login_required
def index(request):
	return render(request, 'users/home.html', {'user': request.user})



def register(request):
	if request.method == 'GET':
		if request.user.is_authenticated():
			return HttpResponseRedirect(reverse('users:index'))
		else:
			return render(request, 'users/register.html', {'page': '1'})
	
	if request.method == 'POST':
		if request.user.is_authenticated():
			return HttpResponseRedirect(reverse('users:index'))
		
		# Get new user credentials from POST
		newusername = request.POST['newusername']
		newpassword1 = request.POST['newpassword1']
		newpassword2 = request.POST['newpassword2']
		newemail = request.POST['newemail']
		newfirstname = request.POST['newfirstname']
		newlastname = request.POST['newlastname']
		
		# Check if passwords fields match
		if newpassword1 != newpassword2:
			content = {
						'username': newusername,
						'email': newemail,
						'firstname': newfirstname,
						'lastname': newlastname,
						'error_message': 'Passwords mismatch',
						'page': '1'
			}
			return render(request, 'users/register.html', content)
		
		# Check if user already exists
		newuser = get_user_model().objects.filter(username=newusername)
		if newuser:
			content = {
						'email': newemail,
						'firstname': newfirstname,
						'lastname': newlastname,
						'error_message': 'This user already exists',
						'page': '1'
			}
			return render(request, 'users/register.html', content)
		
		# Check if email already exists
		newuser = get_user_model().objects.filter(email=newemail)
		if newuser:
			content = {
						'username': newusername,
						'firstname': newfirstname,
						'lastname': newlastname,
						'error_message': 'This email is already taken',
						'page': '1'
			}
			return render(request, 'users/register.html', content)
		
		### Start user creation ###
		
		# Create new User in the system
		newuser = get_user_model().objects.create_user(newusername, newemail, newpassword1)
		newuser.first_name = newfirstname
		newuser.last_name = newlastname
		newuser.email = newemail
		newuser.is_staff = False
		newuser.is_superuser = False
		newuser.is_active = False
		newuser.save()
		
		# Send activation link by email
		sendRegistrationLink(request, newuser)
		
		return render(request, 'users/register.html', {'page': '2'})



def activation(request):
	if request.method == 'GET':
		key = request.GET.get('key', '')
		if key:
			activation = get_object_or_404(ActivationLink, link=key)
			user = activation.user
			user.is_active = True
			user.save()
			
			activation.delete()
			
			if request.user.is_authenticated():
				django.contrib.auth.logout(request)
			
			return render(request, 'users/login.html', {'confirm_message': 'Your account is now active'})
		
		if request.user.is_authenticated():
			# If user is authenticated, it is also active
			return HttpResponseRedirect(reverse('users:index'))
		else:
			return render(request, 'users/activation.html')
		
	if request.method == 'POST':
		if request.user.is_authenticated():
			return HttpResponseRedirect(reverse('users:index'))
		
		# Get user email from POST
		email = request.POST['email']
		
		# Find user object
		try:
			user = get_user_model().objects.get(email=email)
			if not user.is_active:
				sendRegistrationLink(request, user)
		except get_user_model().DoesNotExist:
			pass
		
		return render(request, 'users/activation.html', {'confirm_message': 'Email sent'})



def resetPassword(request):
	if request.method == 'GET':
		if request.user.is_authenticated():
			return HttpResponseRedirect(reverse('users:index'))
		
		return render(request, 'users/reset_password.html')
	
	if request.method == 'POST':
		if request.user.is_authenticated():
			return HttpResponseRedirect(reverse('users:index'))
		
		username = request.POST.get('username', '')
		email = request.POST.get('email', '')
		
		if not username and not email:
			return render(request, 'users/reset_password.html', {'error_message': 'Fill at least one field'})
		
		if username:
			try:
				user = get_user_model().objects.get(username=username)
			except get_user_model().DoesNotExist:
				pass
		else:
			try:
				user = get_user_model().objects.get(email=email)
			except get_user_model().DoesNotExist:
				pass
		
		if user:
			sendPasswordResetLink(request, user)
		
		return render(request, 'users/reset_password.html', {'confirm_message': 'Email sent'})
	



def changePassword(request):
	if request.method == 'GET':
		key = request.GET.get('key', '')
		
		if not key and request.user.is_authenticated():
			content = {
						'user': request.user,
						'username': request.user.username
			}
			return render(request, 'users/change_password.html', content)
		
		passwordReset = get_object_or_404(PasswordResetLink, link=key)
		user = passwordReset.user
		
		if request.user.is_authenticated():
			django.contrib.auth.logout(request)
		
		content = {
					'username': user.username,
					'key': key
		}
		return render(request, 'users/change_password.html', content)
		
	if request.method == 'POST':
		
		key = request.POST.get('key', '')
		
		if key and request.user.is_authenticated():
			django.contrib.auth.logout(request)
		
		if request.user.is_authenticated() or key:
			# Get fields from POST
			if request.user.is_authenticated():
				password = request.POST['password']
			newpassword1 = request.POST['newpassword1']
			newpassword2 = request.POST['newpassword2']
			
			# Check old password
			if request.user.is_authenticated():
				user = django.contrib.auth.authenticate(username=request.user.username, password=password)
				if user is None:
					content = {
								'user': request.user,
								'username': request.user.username,
								'error_message': 'Invalid password'
					}
					return render(request, 'users/change_password.html', content)
			else:
				passwordReset = get_object_or_404(PasswordResetLink, link=key)
				user = passwordReset.user
			
			# Check new password
			if newpassword1 != newpassword2:
				content = {
							'user': request.user,
							'username': request.user.username,
							'error_message': 'Passwords are different'
				}
				return render(request, 'users/change_password.html', content)
			
			# Update password
			if request.user.is_authenticated():
				django.contrib.auth.logout(request)
			else:
				passwordReset.delete()
			user.set_password(newpassword1)
			user.save()
			
			return render(request, 'users/login.html', {'confirm_message': 'Password changed'})
			
		else:
			raise Http404

@login_required
def delete(request):
	if request.method == 'GET':
		return render(request, 'users/delete.html', {'user': request.user})
	

Auth-Server/auth_server/users/templates/users/admin_update.html
{% extends 'users/base_template.html' %}

{% block description %}Administration panel{% endblock %}

{% block title %}Administration panel{% endblock %}

{% block content %}
    
	<form class="form-horizontal" method="post" action="{% url 'users:adminupdate' %}">
		{% csrf_token %}
		<fieldset>
			
		    {% if error_message %}
		    <h4>{{ error_message }}</h4>
		    {% endif %}
			
		    {% if confirm_message %}
		    <h4>{{ confirm_message }}</h4>
		    {% endif %}
    
{% if page == '1' %}

			<!-- Select Basic -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="users">Select user</label>
			  <div class="col-md-4">
				<select id="users" name="users" class="form-control" required>
				  {% for u in userlist %}
				  <option value="{{ u }}">{{ u }}</option>
				  {% endfor %}
				</select>
			  </div>
			</div>
			
			<!-- Button -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="action"></label>
			  <div class="col-md-4">
				<button id="action" name="action" value="next" class="btn btn-primary">Next</button>
			  </div>
			</div>
	
{% elif page == '2' %}
			
			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="account">Username</label>  
			  <div class="col-md-4">
			  <input id="account" name="account" type="text" class="form-control input-md" disabled value="{{ username }}">
				
			  </div>
			</div>

			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="email">Email*</label>  
			  <div class="col-md-4">
			  <input id="email" name="email" type="email" placeholder="email" class="form-control input-md" required value="{{ email }}">
				
			  </div>
			</div>
			
			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="firstname">First name</label>  
			  <div class="col-md-4">
			  <input id="firstname" name="firstname" type="text" placeholder="first name" class="form-control input-md" maxlength="30" value="{{ firstname }}">
				
			  </div>
			</div>
			
			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="lastname">Last name</label>  
			  <div class="col-md-4">
			  <input id="lastname" name="lastname" type="text" placeholder="last name" class="form-control input-md" maxlength="30" value="{{ lastname }}">
				
			  </div>
			</div>
			
			<!-- Button -->
			<div class="form-group" align="right">
			  <label class="col-md-4 control-label" for="action"></label>
			  <div class="col-md-4">
				<button id="action" name="action" value="activate" class="btn btn-success" {% if enabled %}disabled{% endif %}>Activate account</button>
				<button id="action" name="action" value="delete" class="btn btn-danger">Delete account</button>
				<button id="action" name="action" value="update" class="btn btn-primary">Update</button>
			  </div>
			</div>
			
			<input type="hidden" id="username" name="username" value="{{ username }}" />
		
{% endif %}

		</fieldset>
	</form>
		
{% endblock %}

Auth-Server/auth_server/users/templates/users/base_template.html
<!DOCTYPE html>
<html lang="en">
  {% load staticfiles %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block description %}Administration panel{% endblock %}">
    <meta name="author" content="">
    {% block meta %}{% endblock %}
    <link rel="icon" href="{% static 'users/favicon.ico' %}">

    <title>{% block title %}Administration panel{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'users/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'users/custom-css/style.css' %}" rel="stylesheet">
  </head>

  <body>
    
    <!-- Navigation bar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container"> <!-- try with "container-fluid" as alternative -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'users:index' %}">User management</a> <!-- Site title -->
        </div>
        <div id="navbar" class="navbar-collapse collapse">
		
		<!-- Left side -->
		<ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">REST Interface <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li class="dropdown-header">Users</li>
				<li><a href="{% url 'users:gettoken' %}">Token retrieval</a></li>
				<li><a href="{% url 'users:renewtoken' %}">Token renew</a></li>
              </ul>
            </li>
          </ul>
          
          <!-- Right side (account management) -->
          <ul class="nav navbar-nav navbar-right">
{% if user and user.is_authenticated %}
			<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user }} <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
	{% if user.is_superuser %}
                <li class="dropdown-header">Administration</li>
				<li><a href="{% url 'admin:index' %}">Admin page</a></li>
				<li><a href="{% url 'users:adminupdate' %}">Manage users</a></li>
                <li class="divider"></li>
	{% endif %}
                <li class="dropdown-header">User management</li>
				<li><a href="{% url 'users:update' %}">Change personal informations</a></li>
				<li><a href="{% url 'users:password' %}">Change password</a></li>
	{% if not user.is_superuser %}
				<li><a href="{% url 'users:delete' %}">Delete account</a></li>
	{% endif %}
                <li class="divider"></li>
				<li><a href="{% url 'users:logout' %}">Logout</a></li>
              </ul>
            </li>
{% else %}
			<li><a href="{% url 'users:login' %}">Login</a></li>
{% endif %}
          </ul>
          
        </div>
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
	  {% block content %}
	     <!-- Page content -->
	     <h1>Nothing yet!</h1>
	  {% endblock %}
      </div>

    </div><!-- /.container -->



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'users/bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

Auth-Server/auth_server/users/templates/users/delete.html
{% extends 'users/base_template.html' %}

{% block description %}Administration panel{% endblock %}

{% block title %}Login page{% endblock %}

{% block content %}

		<form class="form-horizontal" method="post" action="{% url 'users:delete' %}">
			{% csrf_token %}
			<fieldset>

			<!-- Form Name -->
			<legend>Delete account</legend>
			
		    {% if error_message %}
		    <h4>{{ error_message }}</h4>
		    {% endif %}
			
		    {% if confirm_message %}
		    <h4>{{ confirm_message }}</h4>
		    {% endif %}

{% if user.is_superuser %}
			<h4>You can't delete your account, you are a superuser!</h4>
{% else %}
			<!-- Password input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="password">Password*</label>
			  <div class="col-md-4">
				<input id="password" name="password" type="password" placeholder="Password"
					class="form-control input-md" required autofocus>
				
			  </div>
			</div>

			<!-- Button -->
			<div class="form-group" align="right">
			  <label class="col-md-4 control-label" for="submit"></label>
			  <div class="col-md-4">
				<button id="submit" name="submit" class="btn btn-danger" type="submit">Delete</button>
			  </div>
			</div>
{% endif %}

			</fieldset>
		</form>


{% endblock %}

Auth-Server/auth_server/users/templates/users/home.html
{% extends 'users/base_template.html' %}

{% block description %}Administration panel{% endblock %}

{% block title %}Administration panel{% endblock %}

{% block content %}
    
    <!-- User http://bootsnipp.com/forms?version=3 to generate form to paste here -->
	<form class="form-horizontal">
		<fieldset>

			<!-- Form Name -->
			<legend>Buttons</legend>
			
			<!-- Button -->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="levels">This is a button</label>
			  <div class="col-md-4">
				<a class="btn btn-lg btn-danger" href="#" role="button">GO!</a>
			  </div>
			</div>

		</fieldset>
	</form>

        
{% endblock %}

Auth-Server/auth_server/users/templates/users/login.html
{% extends 'users/base_template.html' %}

{% block description %}Administration panel{% endblock %}

{% block title %}Login page{% endblock %}

{% block content %}

		<form class="form-horizontal" method="post" action="{% url 'users:login' %}">
			{% csrf_token %}
			<fieldset>

			<!-- Form Name -->
			<legend>Please Log-in</legend>
			
		    {% if error_message %}
		    <h4>{{ error_message }}</h4>
		    {% endif %}
			
		    {% if confirm_message %}
		    <h4>{{ confirm_message }}</h4>
		    {% endif %}

			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="username">Username*</label>  
			  <div class="col-md-4">
			  <input id="username" name="username" type="text" placeholder="Username"
					class="form-control input-md" pattern="[a-zA-Z@.+-_]*" maxlength="30"
					required {% if not username %}autofocus{% endif %} value="{{ username }}">
				
			  </div>
			</div>

			<!-- Password input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="password">Password*</label>
			  <div class="col-md-4">
				<input id="password" name="password" type="password" placeholder="Password"
					class="form-control input-md" required {% if username %}autofocus{% endif %}>
				
			  </div>
			</div>

			<!-- Button -->
			<div class="form-group" align="right">
			  <label class="col-md-4 control-label" for="submit"></label>
			  <div class="col-md-4">
				<a href="{% url 'users:register' %}">Register</a> &nbsp;
				<button id="submit" name="submit" class="btn btn-primary" type="submit">Log-in</button>
			  </div>
			</div>
			
			<input type="hidden" id="next" name="next" value="{{ next }}" />

			</fieldset>
		</form>
		<p><a href="{% url 'users:resetpassword' %}">Forgot password?</a></p>
		<p><a href="{% url 'users:activation' %}">Resend activation link</a></p>


{% endblock %}

Auth-Server/auth_server/users/templates/users/register.html
{% extends 'users/base_template.html' %}

{% block description %}Administration panel{% endblock %}

{% block title %}Administration panel{% endblock %}

{% block content %}
    
    {% if page == '1' %}
    
	<form class="form-horizontal" method="post" action="{% url 'users:register' %}">
		{% csrf_token %}
		<fieldset>
			
		    {% if error_message %}
		    <h4>{{ error_message }}</h4>
		    {% endif %}
			
			<!-- Form Name -->
			<legend>Create new user</legend>
			
			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="newusername">Username*</label>  
			  <div class="col-md-4">
			  <input id="newusername" name="newusername" type="text" placeholder="username"
					class="form-control input-md" pattern="[a-zA-Z@.+-_]*" maxlength="30"
					required autofocus value="{{ username }}">
				
			  </div>
			</div>

			<!-- Password input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="newpassword1">Password*</label>
			  <div class="col-md-4">
				<input id="newpassword1" name="newpassword1" type="password" placeholder="password" class="form-control input-md" pattern=".{8,}" required>
				<span class="help-block">Must be at least 8 characters long</span> 
				
			  </div>
			</div>

			<!-- Confirm Password input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="newpassword2">Confirm Password*</label>
			  <div class="col-md-4">
				<input id="newpassword2" name="newpassword2" type="password" placeholder="password" class="form-control input-md" required>
				
			  </div>
			</div>

			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="newemail">Email*</label>  
			  <div class="col-md-4">
			  <input id="newemail" name="newemail" type="email" placeholder="email" class="form-control input-md" required value="{{ email }}">
				
			  </div>
			</div>
			
			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="newfirstname">First name</label>  
			  <div class="col-md-4">
			  <input id="newfirstname" name="newfirstname" type="text" placeholder="name" class="form-control input-md" maxlength="30" value="{{ firstname }}">
				
			  </div>
			</div>
			
			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="newlastname">Last name</label>  
			  <div class="col-md-4">
			  <input id="newlastname" name="newlastname" type="text" placeholder="surname" class="form-control input-md" maxlength="30" value="{{ lastname }}">
				
			  </div>
			</div>
			
			<!-- Button -->
			<div class="form-group" align="right">
			  <label class="col-md-4 control-label" for="submit"></label>
			  <div class="col-md-4">
				<button id="submit" name="submit" type="submit" class="btn btn-primary">Create</button>
			  </div>
			</div>

		</fieldset>
	</form>
	
	{% elif page == '2' %}
		
		<h2>
			Check your inbox!
		</h2>
		<h4>
			An activation link was sent to your email.<br />
			If you encounter any problem visit <a href="{% url 'users:activation' %}">this</a> page.
		</h4>
		
	{% endif %}
		
{% endblock %}

Auth-Server/auth_server/users/templates/users/reset_password.html
{% extends 'users/base_template.html' %}

{% block description %}Administration panel{% endblock %}

{% block title %}Administration panel{% endblock %}

{% block content %}
    
	<form class="form-horizontal" method="post" action="{% url 'users:resetpassword' %}">
		{% csrf_token %}
		<fieldset>
			
		    {% if error_message %}
		    <h4>{{ error_message }}</h4>
		    {% endif %}
			
		    {% if confirm_message %}
		    <h4>{{ confirm_message }}</h4>
		    {% endif %}
			
			<!-- Form Name -->
			<legend>Fill one of these fields</legend>
			
			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="username">Username</label>  
			  <div class="col-md-4">
			  <input id="username" name="username" type="text" placeholder="username" class="form-control input-md" autofocus>
				
			  </div>
			</div>

			<!-- Text input-->
			<div class="form-group">
			  <label class="col-md-4 control-label" for="email">Email</label>  
			  <div class="col-md-4">
			  <input id="email" name="email" type="email" placeholder="email" class="form-control input-md">
				
			  </div>
			</div>
			
			<!-- Button -->
			<div class="form-group" align="right">
			  <label class="col-md-4 control-label" for="submit"></label>
			  <div class="col-md-4">
				<button id="submit" name="submit" type="submit" class="btn btn-primary">Send reset email</button>
			  </div>
			</div>

		</fieldset>
	</form>
		
{% endblock %}